In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentence
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of word',
        'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of word',
 'your videos are good']

In [4]:
#### Define the vocabulary size
voc_size = 10000


In [5]:
## Onehot representation
one_hot_representation =[one_hot(words,voc_size) for words in sent]
one_hot_representation

[[5717, 3157, 354, 882],
 [5717, 3157, 354, 5422],
 [5717, 3318, 354, 3800],
 [9355, 2940, 3299, 1961, 6598],
 [9355, 2940, 3299, 1961, 999],
 [9644, 5717, 3663, 354, 6296],
 [2150, 4827, 6498, 1961]]

In [6]:
## Word Embedding representation

from tensorflow.keras.layers import Embedding
##from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [7]:
import numpy as np

In [20]:
sent_length =8
embedded_docs = pad_sequences(one_hot_representation,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5717 3157  354  882]
 [   0    0    0    0 5717 3157  354 5422]
 [   0    0    0    0 5717 3318  354 3800]
 [   0    0    0 9355 2940 3299 1961 6598]
 [   0    0    0 9355 2940 3299 1961  999]
 [   0    0    0 9644 5717 3663  354 6296]
 [   0    0    0    0 2150 4827 6498 1961]]


In [9]:
# feature representation
dim=10

In [26]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\DeepLearning\Ann\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [29]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[ 3.28405835e-02,  1.69442967e-03, -1.27902627e-02,
          4.70921434e-02,  4.74974401e-02,  1.84304230e-02,
          1.10427625e-02, -2.70495303e-02, -4.08838168e-02,
          4.44099344e-02],
        [ 3.28405835e-02,  1.69442967e-03, -1.27902627e-02,
          4.70921434e-02,  4.74974401e-02,  1.84304230e-02,
          1.10427625e-02, -2.70495303e-02, -4.08838168e-02,
          4.44099344e-02],
        [ 3.28405835e-02,  1.69442967e-03, -1.27902627e-02,
          4.70921434e-02,  4.74974401e-02,  1.84304230e-02,
          1.10427625e-02, -2.70495303e-02, -4.08838168e-02,
          4.44099344e-02],
        [ 3.28405835e-02,  1.69442967e-03, -1.27902627e-02,
          4.70921434e-02,  4.74974401e-02,  1.84304230e-02,
          1.10427625e-02, -2.70495303e-02, -4.08838168e-02,
          4.44099344e-02],
        [ 8.08108598e-04, -8.04462284e-03,  1.01339705e-02,
         -4.05275337e-02, -4.39242721e-02, -2.25602873e-02,
         -3.38471532e-02,  8.12590122e-04,  2.268928